#!/bin/sh

color00="2b/30/3b"
color01="bf/61/6a"
color02="a3/be/8c"
color03="eb/cb/8b"
color04="8f/a1/b3"
color05="b4/8e/ad"
color06="96/b5/b4"
color07="c0/c5/ce"
color08="65/73/7e"
color09=$color01
color10=$color02
color11=$color03
color12=$color04
color13=$color05
color14=$color06
color15="ef/f1/f5"
color16="d0/87/70"
color17="ab/79/67"
color18="34/3d/46"
color19="4f/5b/66"
color20="a7/ad/ba"
color21="df/e1/e8"
color_foreground="c0/c5/ce"
color_background="2b/30/3b"
color_cursor="c0/c5/ce"

if [ -n "$TMUX" ]; then
  printf_template='\033Ptmux;\033\033]4;%d;rgb:%s\033\033\\\033\\'
  printf_template_var='\033Ptmux;\033\033]%d;rgb:%s\033\033\\\033\\'
  printf_template_custom='\033Ptmux;\033\033]%s%s\033\033\\\033\\'
elif [ "${TERM%%-*}" = "screen" ]; then
  printf_template='\033P\033]4;%d;rgb:%s\033\\'
  printf_template_var='\033P\033]%d;rgb:%s\033\\'
  printf_template_custom='\033P\033]%s%s\033\\'
else
  printf_template='\033]4;%d;rgb:%s\033\\'
  printf_template_var='\033]%d;rgb:%s\033\\'
  printf_template_custom='\033]%s%s\033\\'
fi

# 16 color space
printf $printf_template 0  $color00
printf $printf_template 1  $color01
printf $printf_template 2  $color02
printf $printf_template 3  $color03
printf $printf_template 4  $color04
printf $printf_template 5  $color05
printf $printf_template 6  $color06
printf $printf_template 7  $color07
printf $printf_template 8  $color08
printf $printf_template 9  $color09
printf $printf_template 10 $color10
printf $printf_template 11 $color11
printf $printf_template 12 $color12
printf $printf_template 13 $color13
printf $printf_template 14 $color14
printf $printf_template 15 $color15

# 256 color space
printf $printf_template 16 $color16
printf $printf_template 17 $color17
printf $printf_template 18 $color18
printf $printf_template 19 $color19
printf $printf_template 20 $color20
printf $printf_template 21 $color21

if [ -n "$ITERM_SESSION_ID" ]; then
  printf $printf_template_custom Pg c0c5ce
  printf $printf_template_custom Ph 2b303b
  printf $printf_template_custom Pi c0c5ce
  printf $printf_template_custom Pj 4f5b66
  printf $printf_template_custom Pk c0c5ce
  printf $printf_template_custom Pl c0c5ce
  printf $printf_template_custom Pm 2b303b
else
  printf $printf_template_var 10 $color_foreground
  if [ "$BASE16_SHELL_SET_BACKGROUND" != false ]; then
    printf $printf_template_var 11 $color_background
    if [ "${TERM%%-*}" = "rxvt" ]; then
      printf $printf_template_var 708 $color_background
    fi
  fi
  printf $printf_template_custom 12 ";7"
fi

# clean up
unset printf_template
unset printf_template_var
unset color00
unset color01
unset color02
unset color03
unset color04
unset color05
unset color06
unset color07
unset color08
unset color09
unset color10
unset color11
unset color12
unset color13
unset color14
unset color15
unset color16
unset color17
unset color18
unset color19
unset color20
unset color21
unset color_foreground
unset color_background
unset color_cursor
